services:
  nginx:
    image: nginx:latest
    container_name: ftm_nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - app_network
    restart: always

  php-fpm:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: ftm_php_fpm
    volumes:
      - ./:/var/www/html
    networks:
      - app_network
    restart: always

  mariadb:
    image: mariadb:latest
    container_name: ftm_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "4306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ftm_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: ftm_redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

volumes:
  mariadb_data:

networks:
  app_network:
    driver: bridge
